name: ci

on: push

env:
  TZ: "Asia/Tokyo"
  HUGA: "huga"

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setup env
        run: |
          cat .ci.env >> $GITHUB_ENV
      - name: echo
        run: |
          echo $TZ
          echo $HUGA
          echo $HOGE

  run:
    name: run
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: echo
        run: |
          echo $TZ
          echo $HUGA
          echo $HOGE
